name: Build & Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'ui/**'
      - 'api/**'

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy to Azure Static Web App
    permissions:
       contents: read
    steps:
      # Checkout the repo
      - uses: actions/checkout@v3
      # Deploy the application to Azure Static Web Apps
      # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          # App
          skip_app_build: false
          app_location: "./ui" # Location of the built application
          output_location: "dist/home-library/browser"
          app_build_command: "npm run build"
          # API
          skip_api_build: false
          api_location: "./api"
